"""
This type stub file was generated by pyright.
"""

from .SimConnect import DWORD, SimConnect, millis
from .RequestList import AircraftRequests, Request
from .EventList import AircraftEvents, Event
from .FacilitiesList import FacilitiesRequests

def int_or_str(value):  # -> int:
    ...

__version__ = ...
VERSION = ...
__all__ = [
    "SimConnect",
    "Request",
    "Event",
    "millis",
    "DWORD",
    "AircraftRequests",
    "AircraftEvents",
    "FacilitiesRequests",
]
