"""
This type stub file was generated by pyright.
"""

from .Enum import *
from .Constants import *
from ctypes import *
from ctypes.wintypes import *

class SimConnectDll:
    def __init__(self, library_path) -> None: ...
